export const FAILURE_TYPES = 
{
  LOCATOR: "LOCATOR_DRIFT",
  ASSERTION: "ASSERTION_FAILED",
  BACKEND: "BACKEND_FAILURE",
  DATA: "TEST_DATA_ERROR",
  INFRA: "INFRASTRUCTURE",
  TIMEOUT: "TIMEOUT",
  UNKNOWN: "UNKNOWN"
};